person_patterns = [
    {"label": "PERSON", "pattern": "Harry Potter"},
    {"label": "PERSON", "pattern": "Harry"},
    {"label": "PERSON", "pattern": "Potter"},
    {"label": "PERSON", "pattern": "Hermione Granger"},
    {"label": "PERSON", "pattern": "Hermione"},
    {"label": "PERSON", "pattern": "Granger"},
    {"label": "PERSON", "pattern": "Ron Weasley"},
    {"label": "PERSON", "pattern": "Ron"},
    {"label": "PERSON", "pattern": "Weasley"},
    {"label": "PERSON", "pattern": "Albus Dumbledore"},
    {"label": "PERSON", "pattern": "Albus"},
    {"label": "PERSON", "pattern": "Dumbledore"},
    {"label": "PERSON", "pattern": "Severus Snape"},
    {"label": "PERSON", "pattern": "Severus"},
    {"label": "PERSON", "pattern": "Snape"},
    {"label": "PERSON", "pattern": "Rubeus Hagrid"},
    {"label": "PERSON", "pattern": "Rubeus"},
    {"label": "PERSON", "pattern": "Hagrid"},
    {"label": "PERSON", "pattern": "Sirius Black"},
    {"label": "PERSON", "pattern": "Sirius"},
    {"label": "PERSON", "pattern": "Black"},
    {"label": "PERSON", "pattern": "Remus Lupin"},
    {"label": "PERSON", "pattern": "Remus"},
    {"label": "PERSON", "pattern": "Lupin"},
    {"label": "PERSON", "pattern": "Ginny Weasley"},
    {"label": "PERSON", "pattern": "Ginny"},
    {"label": "PERSON", "pattern": "Neville Longbottom"},
    {"label": "PERSON", "pattern": "Neville"},
    {"label": "PERSON", "pattern": "Longbottom"},
    {"label": "PERSON", "pattern": "Draco Malfoy"},
    {"label": "PERSON", "pattern": "Draco"},
    {"label": "PERSON", "pattern": "Malfoy"},
    {"label": "PERSON", "pattern": "Lucius Malfoy"},
    {"label": "PERSON", "pattern": "Lucius"},
    {"label": "PERSON", "pattern": "Bellatrix Lestrange"},
    {"label": "PERSON", "pattern": "Bellatrix"},
    {"label": "PERSON", "pattern": "Lestrange"}
]

org_patterns = [
    {"label": "ORG", "pattern": "Hogwarts"},    
    {"label": "ORG", "pattern": "Ministry of Magic"},    
    {"label": "ORG", "pattern": "Death Eaters"},    
    {"label": "ORG", "pattern": "Order of the Phoenix"},    
    {"label": "ORG", "pattern": "Dumbledore's Army"},    
    {"label": "ORG", "pattern": "Gringotts"},    
    {"label": "ORG", "pattern": "Daily Prophet"},    
    {"label": "ORG", "pattern": "Knights of Walpurgis"},    
    {"label": "ORG", "pattern": "Slug Club"},    
    {"label": "ORG", "pattern": "Inquisitorial Squad"},    
    {"label": "ORG", "pattern": "Sacred Twenty-Eight"},    
    {"label": "ORG", "pattern": "Wizengamot"},    
    {"label": "ORG", "pattern": "St. Mungo's Hospital"},    
    {"label": "ORG", "pattern": "The Quibbler"},    
    {"label": "ORG", "pattern": "International Confederation of Wizards"},    
    {"label": "ORG", "pattern": "Magical Congress of the United States of America"},    
    {"label": "ORG", "pattern": "Gobstones Club"},    
    {"label": "ORG", "pattern": "British Ministry of Magic"},    
    {"label": "ORG", "pattern": "Department of Mysteries"},    
    {"label": "ORG", "pattern": "Department of Magical Law Enforcement"},    
    {"label": "ORG", "pattern": "Department of International Magical Cooperation"},    
    {"label": "ORG", "pattern": "Department of Magical Accidents and Catastrophes"},    
    {"label": "ORG", "pattern": "Department of Magical Transportation"},    
    {"label": "ORG", "pattern": "Department of Magical Games and Sports"},    
    {"label": "ORG", "pattern": "Department of Magical Education"},    
    {"label": "ORG", "pattern": "Department of Magical Maintenance"},    
    {"label": "ORG", "pattern": "Ministry of Magic Maintenance Department"},    
    {"label": "ORG", "pattern": "Office of the Minister for Magic"},    
    {"label": "ORG", "pattern": "Wizengamot Administration Services"},    
    {"label": "ORG", "pattern": "Improper Use of Magic Office"},    
    {"label": "ORG", "pattern": "Muggle-Born Registration Commission"},    
    {"label": "ORG", "pattern": "Snape's Army"},    
    {"label": "ORG", "pattern": "Slug Club"},    
    {"label": "ORG", "pattern": "Dueling Club"},    
    {"label": "ORG", "pattern": "Magical Law Enforcement Patrol"},    
    {"label": "ORG", "pattern": "Department for the Regulation and Control of Magical Creatures"}
]

loc_patterns = [
    {"label": "LOC", "pattern": "Hogwarts"},    
    {"label": "LOC", "pattern": "Diagon Alley"},    
    {"label": "LOC", "pattern": "Hogsmeade"},    
    {"label": "LOC", "pattern": "Azkaban"},    
    {"label": "LOC", "pattern": "Godric's Hollow"},    
    {"label": "LOC", "pattern": "Gringotts"},    
    {"label": "LOC", "pattern": "Ministry of Magic"},    
    {"label": "LOC", "pattern": "Number 12, Grimmauld Place"},    
    {"label": "LOC", "pattern": "The Burrow"},    
    {"label": "LOC", "pattern": "The Leaky Cauldron"},    
    {"label": "LOC", "pattern": "The Forbidden Forest"},    
    {"label": "LOC", "pattern": "Platform Nine and Three-Quarters"},    
    {"label": "LOC", "pattern": "St. Mungo's Hospital for Magical Maladies and Injuries"},    
    {"label": "LOC", "pattern": "The Quidditch World Cup Stadium"},    
    {"label": "LOC", "pattern": "The Room of Requirement"},    
    {"label": "LOC", "pattern": "The Ministry of Magic Atrium"},    
    {"label": "LOC", "pattern": "The Triwizard Maze"},    
    {"label": "LOC", "pattern": "The Great Lake"},    
    {"label": "LOC", "pattern": "The Astronomy Tower"},    
    {"label": "LOC", "pattern": "The Chamber of Secrets"},    
    {"label": "LOC", "pattern": "The Hogwarts Express"},    
    {"label": "LOC", "pattern": "The Prefects' Bathroom"},    
    {"label": "LOC", "pattern": "The Whomping Willow"}
]
    
norp_patterns = [
    {"label": "NORP", "pattern": "Muggles"},    
    {"label": "NORP", "pattern": "Death Eaters"},    
    {"label": "NORP", "pattern": "Goblins"},    
    {"label": "NORP", "pattern": "Giants"},    
    {"label": "NORP", "pattern": "House Elves"},    
    {"label": "NORP", "pattern": "Werewolves"},    
    {"label": "NORP", "pattern": "Vampires"},    
    {"label": "NORP", "pattern": "Veela"},    
    {"label": "NORP", "pattern": "Squibs"},    
    {"label": "NORP", "pattern": "Half-bloods"},    
    {"label": "NORP", "pattern": "Mudbloods"},    
    {"label": "NORP", "pattern": "Pure-bloods"},    
    {"label": "NORP", "pattern": "Slytherins"},    
    {"label": "NORP", "pattern": "Ravenclaws"},    
    {"label": "NORP", "pattern": "Hufflepuffs"},    
    {"label": "NORP", "pattern": "Gryffindors"},    
    {"label": "NORP", "pattern": "Order of the Phoenix"},    
    {"label": "NORP", "pattern": "Dumbledore's Army"},    
    {"label": "NORP", "pattern": "Ministry of Magic"},    
    {"label": "NORP", "pattern": "Inquisitorial Squad"},    
    {"label": "NORP", "pattern": "The Deathly Hallows"},    
    {"label": "NORP", "pattern": "The Marauders"}
] 

product_patterns = [
    {"label": "PRODUCT", "pattern": "broomstick"},    
    {"label": "PRODUCT", "pattern": "wand"},    
    {"label": "PRODUCT", "pattern": "Polyjuice Potion"},    
    {"label": "PRODUCT", "pattern": "Invisibility Cloak"},      
    {"label": "PRODUCT", "pattern": "Remembrall"},    
    {"label": "PRODUCT", "pattern": "Time-Turner"},    
    {"label": "PRODUCT", "pattern": "Pensieve"},    
    {"label": "PRODUCT", "pattern": "Floo Powder"},    
    {"label": "PRODUCT", "pattern": "Portkey"},    
    {"label": "PRODUCT", "pattern": "Flying Ford Anglia"},    
    {"label": "PRODUCT", "pattern": "Hogwarts Express"},    
    {"label": "PRODUCT", "pattern": "Knight Bus"},    
    {"label": "PRODUCT", "pattern": "Firebolt"},    
    {"label": "PRODUCT", "pattern": "Golden Snitch"},    
    {"label": "PRODUCT", "pattern": "Chocolate Frog"},    
    {"label": "PRODUCT", "pattern": "Bertie Bott's Every Flavour Beans"},    
    {"label": "PRODUCT", "pattern": "Butterbeer"},    
    {"label": "PRODUCT", "pattern": "Pumpkin Juice"},    
    {"label": "PRODUCT", "pattern": "Treacle Tart"},    
    {"label": "PRODUCT", "pattern": "Cauldron Cake"},    
    {"label": "PRODUCT", "pattern": "Acid Pops"},    
    {"label": "PRODUCT", "pattern": "Fizzing Whizbees"}
]

money_patterns = [
    {"label": "MONEY", "pattern": "galleons"},  
    {"label": "MONEY", "pattern": "muggle money"},    
    {"label": "MONEY", "pattern": "leprechaun gold"},
    {"label": "MONEY", "pattern": "chocolate frog cards"}
]

entity_patterns = person_patterns + org_patterns + norp_patterns + loc_patterns + product_patterns + money_patterns