greetings = ["Hey, fellow wizarding world fan!",
    "Alohomora, my friend!",
    "Wassup, Quidditch player?",
    "Accio conversation!",
    "Hogwarts is my happy place!",
    "Good morning, Hogwarts hopeful! May your day be filled with the magic of the wizarding world.",
    "Hey there, fellow Potterhead! It's always a good day for some Butterbeer and wizarding fun.",
    "Howdy, Muggle-born! Ready to show the magical world what us wizards are made of?",
    "Aloha, wizarding world fanatic! I hope your day is as enchanting as a ride on a Firebolt broomstick.",
    "Hello, my fellow Deathly Hallows seeker! May your journey be full of wonder and discovery.",
    "Greetings, Gryffindor/Slytherin/Hufflepuff/Ravenclaw! It's a great day to show off our house pride.",
    "Hey, wizarding world enthusiast! Let's explore the secrets of the Room of Requirement together.",
    "Hi, fellow wand-wielder! Let's use our magic to bring some joy and wonder to the world.",
    "Hey, fellow wizarding world adventurer! Are you ready to explore some magical places today?",
    "Hi, fellow Hogwarts alumni! Let's reminisce about our favorite moments from our wizarding education.",
    "Hello, my wizarding world amigo! It's always a good time to cast some spells and brew some potions.",
    "Good day, fellow magical creature enthusiast! Let's discuss our favorite fantastical beasts.",
    "Hey, fellow patronus wielder! Let's spread some positive energy and protect those we love.",
    "Greetings, fellow Order of the Phoenix member! Let's work together to fight against the dark forces.",
    "Hi there, fellow quill and parchment enthusiast! Let's write some enchanting stories together.",
    "Hey, my fellow Ministry of Magic employee! Let's work some magic and make the world a better place.",
    ]

farewells = [
    "Until the next owl delivers our words.",
    "I must be off to catch the Hogwarts Express.",
    "Farewell, and may your spells always find their mark.",
    "I bid thee adieu, and may your broomstick never falter.",
    "Let us part ways for now, but remember that the magic lives within us.",
    "May the sorting hat place you where you truly belong, until we meet again.",
    "I must leave you now, but know that you have the power to make your own magic.",
    "Safe travels, and may the floo network guide you to your destination.",
    "May the patronus that protects you always shine bright, until our paths cross once more.",
    "The conversation has reached its conclusion, but the magic of our words will continue to linger.",
    "Till the next time our wands cross paths, farewell.",
    "May the stars shine bright upon your journey, until we meet again.",
    "Let the magic of our words carry you until our next encounter.",
    "As Dumbledore said, 'Happiness can be found even in the darkest of times,' farewell for now.",
    "May your path be lit by the lumos of knowledge, until we speak again.",
    "Farewell for now, but may the gillyweed of inspiration guide you to new depths.",
    "May the charms of friendship keep us connected, until we meet again.",
    "Our conversation ends, but the enchantment of our connection lingers on.",
    "Let the owls carry our thoughts until we meet again, farewell.",
    "May the magic of our conversation stay with you, until we speak again.",
    "As we part ways, may the wand of your destiny always be at your command.",
    "May the quill of your destiny write a beautiful story, farewell for now.",
    "Our conversation comes to a close, but the door to our friendship remains open.",
    "May your broomstick soar high and true, until we cross paths again.",
    "Our words may end, but the magic of our connection lives on, until we meet again.",
    "May the time-turner of fate bring us together once more, farewell for now.",
    "As the phoenix rises from the ashes, may our conversation ignite the flames of creativity within you.",
    "Our paths may diverge for now, but the patronus of our friendship will always guide us back to one another.",
    "May the spell of good fortune follow you wherever you go, until our next encounter.",
    "Our conversation may end, but the memories of our time together will always be magical."
]

fallbacks = [
    "I'm afraid I can't conjure up a solution to this problem.",
    "I'm no match for the magical forces at work here.",
    "My powers are insufficient to complete this task.",
    "I'm afraid I lack the wizardry required to achieve this feat.",
    "This task is proving to be more elusive than the golden snitch.",
    "I'm as helpless as a Muggle in Diagon Alley.",
    "I'm as powerless as a wand without its wizard.",
    "It seems my spells are no match for the enchantments on this task.",
    "I'm as unsuccessful as Lockhart's attempt to cure a werewolf.",
    "I'm as lost as a first-year in the Forbidden Forest.",
    "This task is as elusive as a Niffler in a jewelry store.",
    "I fear I'm not skilled enough to accomplish this task, even with a wand.",
    "I'm as stumped as Hagrid trying to teach care of magical creatures to a Blast-Ended Skrewt.",
    "It seems this task is as difficult as brewing a potion without the correct ingredients.",
    "I'm as powerless as a spell cast with a broken wand.",
    "This task is proving to be as unyielding as the Whomping Willow.",
    "I'm as unsuccessful as a broomstick without its nimbus charm.",
    "Alas, my magic is not strong enough to overcome the obstacles in this task.",
    "It appears this task is as impossible as discovering the location of the Room of Requirement without knowing the secret.",
    "I'm as helpless as a house elf without its master's orders.",
    "I'm afraid this task is as formidable as facing a Hungarian Horntail.",
    "I'm as powerless as a spell cast during a full moon.",
    "This task is as unattainable as catching the Marauder's Map's creator.",
    "I'm as lost as a kneazle in the Forbidden Forest.",
    "Alas, it seems I'm as helpless as a mermaid on land when it comes to this task.",
    "This task is as challenging as convincing the Ministry of Magic to recognize house-elves as beings.",
    "I'm as ineffective as a wand without its core.",
    "I'm afraid my magic is as weak as Gilderoy Lockhart's memory charm.",
    "This task is as complicated as understanding the language of snakes.",
    "I'm as unsuccessful as a blast-ended skrewt trying to navigate through the Hogwarts maze."
]

repetitions_questions = [
    "I'm sorry, but I'm afraid I already answered that question.",
    "Did you forget? You asked me that already.",
    "I recall you asking me that before. My answer hasn't changed.",
    "Yes, you already asked me that. Is there something else you're curious about?",
    "I think you may have already asked me that question, but if you need more information, I'm happy to try and help!",
    "I'm pretty sure I've already answered that question, but if you're confused about something, feel free to ask again.",
    "I remember you asking me that earlier. Have you thought of any other questions in the meantime?",
    "Ah, yes, I remember that question. My answer hasn't changed since the last time you asked.",
    "You have already asked me that, but if you need a refresher, I'm happy to repeat myself.",
    "I'm sorry, but I think we've covered that topic already. Is there something else you'd like to discuss?",
]

repetitions_statements = [
    "I believe we've already covered that topic, haven't we?",
    "Haven't we already discussed this?",
    "I'm pretty sure we've talked about that before.",
    "You may not remember, but we've already gone over that.",
    "If memory serves, that's something we've already talked about.",
    "I think you might be repeating yourself. We've already addressed that.",
    "Sorry to interrupt, but I think that's something we've already covered.",
    "I don't mean to be rude, but I think you've already said that.",
    "Correct me if I'm wrong, but we've already discussed this, right?",
    "I hate to be a broken record, but we've already talked about that.",
]

exit_strings = ["exit", "quit", "q", "bye", "goodbye", "good bye", "adios", "ciao", "farewell", "finish", "done", "end", "stop", "halt", "cancel", "abort", "close"]
